---
title: "PFE"
author: "Patrice, Stéphane, Fei, test"
date: "23/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# importation des données
```{r}
caracteristiques.2019 <- read.csv2("data/caracteristiques-2019.csv", stringsAsFactors=TRUE)

lieux.2019 <- read.csv2("data/lieux-2019.csv", sep=";", stringsAsFactors=TRUE)

vehicules.2019 <- read.csv("data/vehicules-2019.csv", sep=";")

usagers.2019 <- read.csv("data/usagers-2019.csv", sep=";")


View(caracteristiques.2019)
colnames(caracteristiques.2019)
str(caracteristiques.2019)

```

# creation de variables de securite
## secu_or_not : s'il y a au moins une équipement de securité
## secu_level : nb d'équipements de sécurité
```{r}
usagers.2019 <- usagers.2019 %>% mutate(secu_or_not = (secu1 %in% c("1", "2","3","4","5", "6","7")) | (secu2 %in% c("1", "2","3","4","5", "6","7")) | (secu3 %in% c("1", "2","3","4","5", "6","7")), secu_level = (secu1 %in% c("1", "2","3","4","5", "6","7")) + (secu2 %in% c("1", "2","3","4","5", "6","7")) + (secu3 %in% c("1", "2","3","4","5", "6","7")))


grav <- usagers.2019 %>% group_by(grav) %>% summarise(total=n())
grav_secu <- 
inner_join(usagers.2019 %>% filter(grav !=1) %>%  group_by(grav, secu_or_not) %>% summarise(n=n()), grav, by = "grav") %>% mutate(pourcentage = n/total) %>% mutate(lab_ypos = cumsum(n))
lab_ypos_2 = c(3498, 1391, 20858, 6240, 53307, 12878)
c <- cbind(grav_secu, lab_ypos_2)

colnames(c) <- c("grav",        "secu_or_not", "n",           "total"   ,  
"pourcentage", "lab_ypos",    "lab_ypos2") 


library(ggplot2)
ggplot(data = c, aes(x = grav, y = n)) +
  geom_col(aes(fill = secu_or_not), width = 0.7)+
  geom_text(aes(y = lab_ypos2/1.2, label = round(pourcentage, digits = 2), group =secu_or_not), color = "white")

```

# jointure des tables
## il suffit d'utiliser inner join car les tables se correspondent

```{r}
library(tidyverse)
acc_place_19 <- inner_join(caracteristiques.2019,lieux.2019,by=c("Num_Acc"="Num_Acc"));

user_car_19<- inner_join(vehicules.2019,usagers.2019,by=c("Num_Acc"="Num_Acc", "id_vehicule" = "id_vehicule", "num_veh" = "num_veh"));

total_19 <- inner_join(acc_place_19,user_car_19,by=c("Num_Acc"="Num_Acc"));

```

# Geolocalisation pour les accidents du département 59 en 2019. Trop consommant si on ne filter pas un seul departement

```{r}
caracteristiques.2019.59 <- caracteristiques.2019 %>% filter(grepl('^59',com))

library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=caracteristiques.2019.59$long, lat=caracteristiques.2019.59$lat , popup=caracteristiques.2019.59$adr)
m  
```

# stat desc
```{r}
total_19 %>% summarise()
colnames(total_19)
```
```{r}
total_19 %>% summarise()
colnames(total_19)
```

